### ISSUE TITLE
Select2ServiceProvider的28行Form::registerBuiltinFields()导致扩展加载异常问题。

### ISSUE THREAD

**Issue by ayousoft** [xiaohuilam/laravel-admin-select2#28]
Select2ServiceProvider的28行Form::registerBuiltinFields()会导致app/bootstrap.php的 Encore\Admin\Form::forget(['map', 'editor']) 配置失效。请问组件是用到这两个扩展吗？

**Comment by ayousoft** [comment]
请问 Form::registerBuiltinFields() 再次初始化的作用是什么？我看laravel-admin有过一次初始化了，是否重复了？

**Comment by xiaohuilam** [comment]
这应该是一个bug（覆盖了app/admin/bootstrap.php的定义），我会尽快跟进
